Repository ItJustWorksBetterTM/EiffelVis, pull requests merged in 2022-11, with the labels that each got.

#39 Remove playground code and update README
  README.md
  backend/src/main.rs
  backend/tools/event_sender/src/main.rs
Labels: documentation

#32 Us4 display node on hover
  backend/crates/eiffelvis_core/src/domain/types.rs
  frontend/src/App.svelte
  frontend/src/components/G6Graph.svelte
  frontend/webpack.config.js
Labels: enhancement, Sprint4

#44 Bug fix - When generating nodes without datadump
  backend/tools/event_sender/src/main.rs
Labels: bug

#43 Wildcard filtering
  backend/crates/eiffelvis_core/src/domain/user_queries.rs
Labels: enhancement, Filter
